package com.snippets.demo.bean;

public enum EmployeeImportHeader {
	STATUS, USERID, USERNAME;
	//FIRSTNAME, MIDDLENAME, LASTNAME, TITLE, GENDER, EMAIL, MANAGER, HR, DEPARTMENT, JOBCODE, DIVISION,
	// LOCATION, TIMEZONE, HIREDATE, EMPID, TITLE, BIZ_PHONE, FAX, ADDR1, ADDR2,
	// CITY, STATE, ZIP, COUNTRY, REVIEW_FREQ, LAST_REVIEW_DATE, MATRIX_MANAGER,
	// DEFAULT_LOCALE, PROXY, seatingChart, REVIEW_FREQ, LAST_REVIEW_DATE,
	// CUSTOM01, CUSTOM02, CUSTOM03, CUSTOM04, CUSTOM05, CUSTOM06, CUSTOM07,
	// CUSTOM08, CUSTOM09, CUSTOM10, CUSTOM11, CUSTOM12, CUSTOM13, CUSTOM14,
	// CUSTOM15, ONBOARDING_ID
}
